---
- name: Postgres installation and configuration
  hosts: nodo1
  become: true
  tasks:
  - name: Ensure postgres is installed
    apt: pkg={{item}}
    with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2

  - name: Ensure the PostgreSQL service is running
    service: name=postgresql state=started enabled=yes

  - name: Create database to Drupal
    become: yes
    become_user: postgres
    vars:
      ansible_ssh_pipelining: true
    postgresql_db:
      name: drupaldb
      encoding: UTF-8

  - name: Create database user Drupal
    become: yes
    become_user: postgres
    vars:
      ansible_ssh_pipelining: true
    postgresql_user:
      db: drupaldb
      name: drupal
      password: drupal
      priv: "ALL"
      expires: infinity

    notify:
      - restart postgresql

  - name: Configure pg_hba.conf
    copy:
      src=conf/pg_hba.conf
      dest=/etc/postgresql/9.6/main/pg_hba.conf

  - name: Configure postgresql.conf
    copy:
      src=conf/postgresql.conf
      dest=/etc/postgresql/9.6/main/postgresql.conf

    notify:
      - restart postgresql

  handlers:
    - name: restart postgresql
      command: systemctl restart postgresql
