---
- name: Postgres installation and configuration
  hosts: all
  become: true
  tasks:
  - name: Ensure packages are installed
    apt: pkg=postgresql

  - name: Ensure the PostgreSQL service is running
    service: name=postgresql state=started enabled=yes

  - name: Create database to Drupal
    become: yes
    become_user: postgres
    vars:
      ansible_ssh_pipelining: true
    postgresql_db:
      name: drupaldb
      encoding: UTF-8

  - name: Create database user Drupal
    become: yes
    become_user: postgres
    vars:
      ansible_ssh_pipelining: true
    postgresql_user:
      db: drupaldb
      name: drupal
      password: drupal
      priv: "ALL"
      expires: infinity

    notify:
      - restart postgresql
